version: '3'
services:
  scraper:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - ./data:/usr/src/app/data
      - './scraping_credentials.json:/app/scraping_credentials.json:ro'
    environment:
      - PYTHONUNBUFFERED=1
    command: python scraper.py
    tty: true
    stdin_open: true

  send_to_sheets:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - ./data:/usr/src/app/data
      - './scraping_credentials.json:/app/scraping_credentials.json:ro'
    environment:
      - PYTHONUNBUFFERED=1
    command: python send_to_sheets.py
    tty: true
    stdin_open: true
